package com.mixshare.rapid_evolution.audio.tags.util;

import java.util.Vector;

public class GenreUtil {

	static private Vector<String> genres = new Vector<String>(147);
	
	static {
		genres.add("Blues"); 
		genres.add("Classic Rock"); 
		genres.add("Country"); 
		genres.add("Dance"); 
		genres.add("Disco"); 
		genres.add("Funk"); 
		genres.add("Grunge"); 
		genres.add("Hip-Hop"); 
		genres.add("Jazz"); 
		genres.add("Metal");  
		genres.add("New Age");  
		genres.add("Oldies");  
		genres.add("Other");  
		genres.add("Pop");  
		genres.add("R&B");  
		genres.add("Rap");  
		genres.add("Reggae");  
		genres.add("Rock");  
		genres.add("Techno");  
		genres.add("Industrial");  
		genres.add("Alternative");  
		genres.add("Ska");  
		genres.add("Death Metal");  
		genres.add("Pranks");  
		genres.add("Soundtrack");  
		genres.add("Euro-Techno");  
		genres.add("Ambient");  
		genres.add("Trip-Hop");  
		genres.add("Vocal");  
		genres.add("Jazz+Funk");  
		genres.add("Fusion");  
		genres.add("Trance");  
		genres.add("Classical");  
		genres.add("Instrumental");  
		genres.add("Acid");  
		genres.add("House");  
		genres.add("Game");  
		genres.add("Sound Clip");  
		genres.add("Gospel");  
		genres.add("Noise");  
		genres.add("Alternative Rock");  
		genres.add("Bass");  
		genres.add("Soul");  
		genres.add("Punk");  
		genres.add("Space");  
		genres.add("Meditative");  
		genres.add("Instrumental Pop");  
		genres.add("Instrumental Rock");  
		genres.add("Ethnic");  
		genres.add("Gothic");  
		genres.add("Darkwave");  
		genres.add("Techno-Industrial");  
		genres.add("Electronic");  
		genres.add("Pop-Folk");  
		genres.add("Eurodance");  
		genres.add("Dream");  
		genres.add("Southern Rock");  
		genres.add("Comedy");  
		genres.add("Cult");  
		genres.add("Gangsta");  
		genres.add("Top 40");  
		genres.add("Christian Rap");  
		genres.add("Pop/Funk");  
		genres.add("Jungle");  
		genres.add("Native US");  
		genres.add("Cabaret");  
		genres.add("New Wave");  
		genres.add("Psychadelic");  
		genres.add("Rave");  
		genres.add("Showtunes");  
		genres.add("Trailer");  
		genres.add("Lo-Fi");  
		genres.add("Tribal");  
		genres.add("Acid Punk");  
		genres.add("Acid Jazz");  
		genres.add("Polka");  
		genres.add("Retro");  
		genres.add("Musical");  
		genres.add("Rock & Roll");  
		genres.add("Hard Rock");  
		genres.add("Folk");  
		genres.add("Folk-Rock");  
		genres.add("National Folk");  
		genres.add("Swing");  
		genres.add("Fast Fusion");  
		genres.add("Bebob");  
		genres.add("Latin");  
		genres.add("Revival");  
		genres.add("Celtic");  
		genres.add("Bluegrass");  
		genres.add("Avantgarde");  
		genres.add("Gothic Rock");  
		genres.add("Progressive Rock");  
		genres.add("Psychedelic Rock");  
		genres.add("Symphonic Rock");  
		genres.add("Slow Rock");  
		genres.add("Big Band");  
		genres.add("Chorus");  
		genres.add("Easy Listening");  
		genres.add("Acoustic");  
		genres.add("Humour");  
		genres.add("Speech");  
		genres.add("Chanson");  
		genres.add("Opera");  
		genres.add("Chamber Music");  
		genres.add("Sonata");  
		genres.add("Symphony");  
		genres.add("Booty Bass");  
		genres.add("Primus");  
		genres.add("Porn Groove");  
		genres.add("Satire"); 
		genres.add("Slow Jam"); 
		genres.add("Club"); 
		genres.add("Tango"); 
		genres.add("Samba"); 
		genres.add("Folklore"); 
		genres.add("Ballad"); 
		genres.add("Power Ballad"); 
		genres.add("Rhythmic Soul"); 
		genres.add("Freestyle"); 
		genres.add("Duet"); 
		genres.add("Punk Rock"); 
		genres.add("Drum Solo"); 
		genres.add("Acapella"); 
		genres.add("Euro-House"); 
		genres.add("Dance Hall"); 
		genres.add("Goa"); 
		genres.add("Drum & Bass"); 
		genres.add("Club - House"); 
		genres.add("Hardcore"); 
		genres.add("Terror"); 
		genres.add("Indie"); 
		genres.add("BritPop"); 
		genres.add("Negerpunk"); 
		genres.add("Polsk Punk"); 
		genres.add("Beat"); 
		genres.add("Christian Gangsta Rap"); 
		genres.add("Heavy Metal"); 
		genres.add("Black Metal"); 
		genres.add("Crossover"); 
		genres.add("Contemporary Christian"); 
		genres.add("Christian Rock"); 
		genres.add("Merengue"); 
		genres.add("Salsa"); 
		genres.add("Thrash Metal"); 
		genres.add("Anime"); 
		genres.add("JPop"); 
		genres.add("Synthpop"); 	
	}
	
	static public String getGenre(int index) {
		return genres.get(index);		
	}
	
}
